### ISSUE TITLE
Magento | one installation - three different websites setup

### ISSUE THREAD

**Issue by nirant-sardar-pp** [pointspay/pointspay-magento#1]
Hi @teodoramodoranovic ,
Task: one magento installation/instance and configuring three different websites to work simultaneously.

Brif about issue -
We have one merchant integrating the existing magento plugin. In website scope they have three different websites/ stores.  
When we tested on merchant's test environment, we were able to configure three different shops with 3 different set of API credentials.
But when payment requests were made, correct consumer key was not getting picked up which is associated to shop, instead different shop's consumer is being used for signature generation. Thus signature verification fails.

Could you please have a look at the issue and see if you can replicate it ?

**Comment by DamjanLogeecom** [comment]
Hello @nirant-sardar-pp,

Note that our team is checking the reported issue.

As soon as we have some valid information to provide, we will let you know.

Thank you,

Kind regards
Logeecom Team

**Comment by vlaskinvlad** [comment]
reopen it later

**Comment by RogierJacobson** [comment]
@vlaskinvlad : it is not clear to me: has this been verified and can we rollout new plugin with Mixx Shabbies? Teodora and team are not looking into this after you closing the ticket.

**Comment by RogierJacobson** [comment]
@teodoramodoranovic  : so we checked and indeed we would like you and the team to verify this one based on the new plugin. We have a few merchants that are depending on this one.
Thanks @DamjanLogeecom  FYI

**Comment by RogierJacobson** [comment]
Task: one magento installation/instance and configuring three different websites to work simultaneously.

On our internal test environment:

Magento installation and end to end testing on one shop is completed.
Three websites / shops configuration is completed .
Configuring the domain and three different shop URL’s is pending .Infra team need to do it.
Brif about issue -
When we tested on merchant's test environment, correct consumer kay was not getting picked up which is associated to shop, instead different shop's consumer is being used for signature generation. Thus signature verification fails.
Prespective say -
there is some customization on merchant side causing this.
What we will do -
we will do same setup on our test environment and magento shop/s and verify the issue.

**Comment by RogierJacobson** [comment]
Magento's version - 2.4.5-p8 


Adding the PDF with old Jira ticket for reference as well

[[#PKB-3] Mexx Onboarding_FB merchant_Magento.pdf](https://github.com/user-attachments/files/17978866/PKB-3.Mexx.Onboarding_FB.merchant_Magento.pdf)
