### ISSUE TITLE
Prestashop x ezkrt Integration Error

### ISSUE THREAD

**Issue by PriyankaAggarwal23** [pointspay/pointspay-magento#7]
We are encountering a "Bad Request" error while attempting to redirect to the payment page after login to the Etihad GuestPay account in staging environment. Could you kindly assist us in resolving this issue? 

Access to test shop: https://b2cclone.ezkrt.com/
Login creds: test@test.com / Oma@1234

Access to the admin portal: https://b2cclone.ezkrt.com/admin093hccxap
Login creds: priyanka.aggarwal@pointspay.com / Pr!y@nka#2024 

Etihad test login creds: 420000021814/ Pointspay@123

Screenshot of the error:

 ![Image](https://github.com/user-attachments/assets/860a07a2-2c65-4309-94f9-a80731276436)

**Comment by DamjanLogeecom** [comment]
Hello @PriyankaAggarwal23,

Thank you for reaching out to us regarding this issue.

Could you provide us with the Prestashop version that this merchant is using?

Thank you,

Kind regards.

**Comment by PriyankaAggarwal23** [comment]
@DamjanLogeecom They are using Prestashop 1.7.8.0.

**Comment by PriyankaAggarwal23** [comment]
@DamjanLogeecom Its working again. 

![image](https://github.com/user-attachments/assets/fbeba1eb-b36b-4d28-842e-0908f2cee958)

**Comment by DamjanLogeecom** [comment]
Hello @PriyankaAggarwal23,

Note that our team finished reviewing the issue you raised.

Our team noticed that the Pointspay payment method is configured with data that is reserved for the Etihad Guestpay payment method:
![Image](https://github.com/user-attachments/assets/17300443-a2c1-4934-a355-82ab18a1396a)
On checkout, even though the Pointspay payment method is configured, we can see that the Etihad Guestpay payment method logo is being displayed, indicating that the data used for the Poinstpay connection is that of the Etihad Guestpay payment method:
![Image](https://github.com/user-attachments/assets/35d1be27-43d6-41fa-b5a6-b1e9fd338cca)
Could you please advise the merchant to take the same connection data and configure it for Etihad Guestpay in the plugin?
![Image](https://github.com/user-attachments/assets/57c4cafe-98ee-44ed-be73-30e4c0aeccd2)
Additionally, note that Etihad Guestpay payment method is not working as expected at the moment. This was reported on our end by Aleksandar Boljanovic in our shared Slack channel.

If you have any questions, feel free to let us know.

Kind regards.

**Comment by PriyankaAggarwal23** [comment]
Thanks for the quick feedback @DamjanLogeecom. Merchant has updated the configuration but I still see the same error while redirecting to the payment page after login. 
One thing I noticed is the last digits of the private key displayed in the plugin does not match with the certificate downloaded. 

For eg: Attaching the ss from the plugin and the certificate.
![image](https://github.com/user-attachments/assets/ab5d121a-269a-4233-85b3-e7541f2b4d7b)
[pointspay_certificate (1).zip](https://github.com/user-attachments/files/18230558/pointspay_certificate.1.zip)

**Comment by DamjanLogeecom** [comment]
Hello @PriyankaAggarwal23,

We checked with our dev team and we can confirm that the Private key should not match any certificate. The certificates are generated based on the private key value.

Additionally, when a redirection from the shop happens (on checkout, after clicking on “Order Now” the user is led to another site that is not the shop) that means that the certificates have been configured correctly. If the certificates are not correctly configured, no redirection happens and an error message is displayed on checkout. Our integration only handles this redirection.

The issue with Etihad GuestPay in this case is not on the integration side and this is something that your team should take a look at.

Please let us know if you manage to get any additional information for Etihad on your end or if there is anything else you need from our team.

Thank you,

Kind regards.

**Comment by PriyankaAggarwal23** [comment]
Thanks a lot @DamjanLogeecom, our tech team has identified that the issue is from Etihad side and not from plugin.
